name: Test package

on: [push, pull_request, pull_request_target]

jobs:
  build-ubuntu-latest:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 6
      matrix:
        python-version: [3.11.x]
        test-tool: [pylint]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools
          pip install -r requirements.txt
      - name: Test with ${{ matrix.test-tool }}
        run: |
          pip install ${{ matrix.test-tool }}
          tests/run_tests.sh ${{ matrix.test-tool }}
